### ISSUE TITLE
关于里程计的使用

### ISSUE THREAD

**Issue by oscar1780** [Guo-ziwei/fusion#3]
作者您好，关于里程计使用部分，我看您的代码里面是将 里程计的 位置测量值 赋值给 GPS因子初值 然后做优化，请问可以这样做的原理可以简单讲一下么？     
代码部分：GPSFactor gps_factor(X(correction_count), Point3(odom(0), odom(1), odom(2)), correction_noise);
我理解的 wheel odometry的测量值应该是 线速度 和 角速度，GPS的频率远低于 IMU 和 wheel， 所以应该使用预积分的方式计算imu和wheel 里程计。

**Comment by Guo-ziwei** [comment]
这里我觉得就是看怎样处理里程计的观测值，我这里是将里程计作为两帧间的相对位姿的测量（其实就是对线速度和角速度的一个积分），将线速度和角速度作为观测也是一样的，至于预积分的计算方式，因为GPS前后两帧都是独立观测，IMU的噪声也不在状态向量里，所以我就简单处理了，当然也可以使用预积分

**Comment by oscar1780** [comment]
> 

了解了，我自己先尝试改试一下，谢谢回复。
