### ISSUE TITLE
有没有论文或文档可以参考呢？

### ISSUE THREAD

**Issue by Gatsby23** [Guo-ziwei/fusion#4]
很不错的工作，不好意思，这边想咨询一下是否有相关的论文和文档可以参考呢？

**Comment by Guo-ziwei** [comment]
这个demo里面的内容比较杂，一部分是EKF的内容，GTSAM的内容主要参开GTSAM(https://github.com/borglab/gtsam)的官方仓库里面的例子。大部分是我读研究生事情搞的
