### ISSUE TITLE
ROS编译出错

### ISSUE THREAD

**Issue by st2020-2020** [Guo-ziwei/fusion#5]
感觉老哥的分享！
但是我在Ubuntu16.04 ROS kinetic环境下编译不成功，出现了**gtsam_imu/src/Mestimators.cpp:161:16: error: ‘class gtsam::NonlinearFactorGraph’ has no member named ‘addPrior’**  的报错信息，请问该怎么解决？
还有一个问题想请教，EFK那个功能包跑出来的结果只在终端输出，输出的数据该怎么处理和画图展示？

**Comment by Guo-ziwei** [comment]
`        // Print to stdout as plot format
        std::cout << 0.0 << " " << 0.0 << " " << x_ekf.x() << " " << x_ekf.y() << " " << x_ekf.z() << " " << x_ekf.qx()
                  << " " << x_ekf.qy() << " " << x_ekf.qz() << " " << x_ekf.qw() << std::endl;`
我这里是按照TUM格式输出的，我当时是把结果存储在文本中，然后用python脚本绘制结果，方法有很多

第一个问题的话，应该不是GTSAM版本问题，这个函数在很老的版本里就有了，可能是gtsam库编译时遇到了问题？这个我不确定，不过你可以去gtsam库里搜一下，这个函数时一定有的

**Comment by st2020-2020** [comment]
感谢老哥深夜及时的回复！
TUM格式的数据我还没有太了解过，能麻烦你分享一下你用的py脚本吗？
gtsam我编译倒是很顺利没有出错，我到时候再去源码里看看问题吧，再次感谢老哥的解答

**Comment by Guo-ziwei** [comment]
我在欧洲出差，脚本我手头没有现成的，matplotlib上有很多demo，足够绘制线条了，不麻烦

**Comment by st2020-2020** [comment]
感谢老哥，我用evo工具绘制成功了！

**Comment by xl232lx** [comment]
你好，我编译之后会出现如下打印：
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libgtsam_unstable.so: undefined reference to `gtsam::GaussianFactorGraph::optimize(gtsam::Ordering const&, boost::function<std::pair<boost::shared_ptr<gtsam::GaussianConditional>, boost::shared_ptr<gtsam::GaussianFactor> > (gtsam::GaussianFactorGraph const&, gtsam::Ordering const&)> const&) const'
请问这是啥问题？我的gtsam版本是4.2a8

**Comment by Guo-ziwei** [comment]
> 你好，我编译之后会出现如下打印： /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libgtsam_unstable.so: undefined reference to `gtsam::GaussianFactorGraph::optimize(gtsam::Ordering const&, boost::function<std::pair<boost::shared_ptrgtsam::GaussianConditional, boost::shared_ptrgtsam::GaussianFactor > (gtsam::GaussianFactorGraph const&, gtsam::Ordering const&)> const&) const' 请问这是啥问题？我的gtsam版本是4.2a8

可能是gtsam版本比较新，这个api已经从unstable移出了？
