### ISSUE TITLE
what is the bag file? 

### ISSUE THREAD

**Issue by himhan34** [Guo-ziwei/fusion#6]
hello i am himhan3455, 
and i want to know what is the bag file, i mean , is that a all recorded bag file, like 
odom, imu/dat etc combined data ?  thanks for reading! 
have a nice day!

**Comment by Guo-ziwei** [comment]
yes, the rosbag I used to do the demo is from this (https://projects.csail.mit.edu/stata/downloads.html) dataset. The bag combined  Laser, IMU and wheel odom data.
